#define SID_SYSTEM_EXIT     "Exit"
#define SID_SYSTEM_COLOR    "Color"
#define SID_SYSTEM_DATABASE "Database"
#define SID_SYSTEM_DEFAULT_MAP "Buckwwalter"
#define SID_SYSTEM_DOCKED    "Docked"
#define SID_SYSTEM_FOCUS_TAB "Focus tab"
#define SID_SYSTEM_INTERFACE "Interface"
#define SID_SYSTEM_KEYMAPS   "Keymaps"
#define SID_SYSTEM_NAV_MODE  "Nav mode"
#define SID_SYSTEM_OPEN_LINK "Open links in current tab"
#define SID_SYSTEM_ACTIVATE_LINK "Always Make link active"

#define SID_SPLASH_DELAY "Delay"
#define SID_SPLASH_ENABLED "Enabled"
#define SID_SPLASH_LOCATION "Location"
#define SID_SYSTEM_ARABIC_FONT "Arabic font"
/*

These are the keys to access values in the INI file.

Format is SID_<section name>_<unique id>

They should be used whenever qsetttingsvalue() or qsettings.setValue() is called
They should not be translated.

 */
#define SID_ENTRY_BACK "Back"
#define SID_ENTRY_CSS  "CSS"
#define SID_ENTRY_CLEAN "Clean"
#define SID_ENTRY_CLEAR_SCENE "Clear scene"
#define SID_ENTRY_DEBUG "Debug"
#define SID_ENTRY_FIND  "Find"
#define SID_ENTRY_FIND_NEXT "Find next"
#define SID_ENTRY_FORWARD  "Forward"
#define SID_ENTRY_FONT_SIZE "Font size"
#define SID_ENTRY_HOME       "Home"
#define SID_ENTRY_MARGIN     "Margin"
#define SID_ENTRY_MARK     "Mark"
#define SID_ENTRY_MOVE_FOCUS_UP "Move focus up"
#define SID_ENTRY_MOVE_FOCUS_DOWN "Move focus down"
#define SID_ENTRY_NARROW  "Narrow"
#define SID_ENTRY_RELOAD    "Reload"
#define SID_ENTRY_SCALE   "Scale"
#define SID_ENTRY_SHOW    "Show"
#define SID_ENTRY_STEP    "Step"
#define SID_ENTRY_HIGHLIGHT_COLOR "Highlight color"
#define SID_ENTRY_TEXT_WIDTH "Text width"
#define SID_ENTRY_WIDEN   "Widen"

#define SID_ENTRY_ZOOM_IN "Zoom in"
#define SID_ENTRY_ZOOM_OUT "Zoom out"
#define SID_ENTRY_PRINT_CSS "Print Css"
#define SID_ENTRY_DUMP_HTML "Save Html"
#define SID_ENTRY_DUMP_XML  "Save Xml"
#define SID_ENTRY_DUMP_OUTPUT_HTML "Save output Html"
#define SID_ENTRY_SHOW_LINK_WARNING  "Show link warning"

#define SID_XSLT_ENTRY   "Entry"
#define SID_XSLT_NODE   "Node"
#define SID_XSLT_PRINT   "Print"

#define SID_NOTES_ENABLED "Enabled"



#define SID_SHORTCUT_COLLAPSE_ALL "Collapse all"


#define SID_ROOTS_DEBUG "Debug"
#define SID_ROOTS_EXPAND "Expand"
#define SID_ROOTS_KEEP_FOCUS "Keep focus"
#define SID_ROOTS_MOVE_UP "Move up"
#define SID_ROOTS_MOVE_DOWN "Move down"
#define SID_ROOTS_BACKGROUND_COLOR "Background"
#define SID_ROOTS_ITYPE_FONT "Itype font"


#define SID_PRINTER_NAME "Name"
#define SID_PRINTER_ORIENTATION "Orientation"
#define SID_PRINTER_RESOLUTION "Resolution"
#define SID_PRINTER_PAPER_SIZE "Paper size"
#define SID_PRINTER_COPIES "Copies"
#define SID_PRINTER_FULL_PAGE "Full page"
#define SID_PRINTER_USE "Use"
#define SID_PRINTER_OUTPUT_PDF "Output to PDF"
#define SID_PRINTER_PDF_DIRECTORY "PDF directory"
#define SID_PRINTER_AUTONAME_PDF "Autoname PDF"
#define SID_PRINTER_AUTONAME_METHOD "Naming method"




#define SID_SHORTCUT_BOOKMARK_ADD              "Bookmark add"
#define SID_SHORTCUT_CONTENTS_COLLAPSE_ALL     "Contents collapse all"
#define SID_SHORTCUT_CONTENTS_COLLAPSE_LETTER  "Contents collapse letter"
#define SID_SHORTCUT_CONTENTS_SHOW             "Contents show"
#define SID_SHORTCUT_CONVERT_TO_ENTRY          "Convert to entry"
#define SID_SHORTCUT_DELETE_TAB                "Delete tab"
#define SID_SHORTCUT_DELETE_OTHER_TABS         "Delete other tabs"
#define SID_SHORTCUT_FOCUS_CONTENT             "Focus content"
#define SID_SHORTCUT_FOCUS_TREE                "Focus tree"
#define SID_SHORTCUT_GO_TAB                    "Go Tab"
#define SID_SHORTCUT_HISTORY_BACK              "History back"
#define SID_SHORTCUT_HISTORY_NEXT              "History next"
#define SID_SHORTCUT_HISTORY_LIST              "History list"
#define SID_SHORTCUT_HISTORY_CLEAR             "History clear"
#define SID_SHORTCUT_HISTORY_ENABLE            "History enable"
#define SID_SHORTCUT_HISTORY_DISABLE           "History disable"
#define SID_SHORTCUT_KEYMAPS_DISABLE           "Keymaps disable"
#define SID_SHORTCUT_KEYMAPS_ENABLE            "Keymaps enable"
#define SID_SHORTCUT_LOCAL_SEARCH              "Local search"
#define SID_SHORTCUT_LOCAL_SEARCH_CLEAR        "Local search clear"
#define SID_SHORTCUT_LOCAL_SEARCH_FIND         "Local search find"
#define SID_SHORTCUT_LOCAL_SEARCH_NEXT         "Local search next"
#define SID_SHORTCUT_LOCAL_SEARCH_SHOW         "Local search show"
#define SID_SHORTCUT_NAV_PAGE_MODE             "Nav Page mode"
#define SID_SHORTCUT_NAV_ROOT_MODE             "Nav Root mode"
#define SID_SHORTCUT_NAV_FIRST                 "Go first"
#define SID_SHORTCUT_NAV_NEXT                  "Go next"
#define SID_SHORTCUT_NAV_PREV                  "Go prev"
#define SID_SHORTCUT_NAV_LAST                  "Go last"

/*
#define SID_SHORTCUT_PAGE_FIRST                "Page first"
#define SID_SHORTCUT_PAGE_LAST                 "Page last"
#define SID_SHORTCUT_PAGE_NEXT                 "Page next"
#define SID_SHORTCUT_PAGE_PREV                 "Page prev"
#define SID_SHORTCUT_ROOT_FIRST                "Root first"
#define SID_SHORTCUT_ROOT_LAST                 "Root last"
#define SID_SHORTCUT_ROOT_NEXT                 "Root next"
#define SID_SHORTCUT_ROOT_PREV                 "Root prev"
*/
#define SID_SHORTCUT_PAGE_SEARCH               "Page search"
#define SID_SHORTCUT_QUIT                      "Quit"
#define SID_SHORTCUT_SEARCH_DELETE             "Search delete"
#define SID_SHORTCUT_SEARCH_ENTRY              "Search entry"
#define SID_SHORTCUT_SEARCH_HEAD               "Search head"
#define SID_SHORTCUT_SEARCH_NODE               "Search node"
#define SID_SHORTCUT_SEARCH_ROOT               "Search root"
#define SID_SHORTCUT_SEARCH_WORD               "Search word"
#define SID_SHORTCUT_SEARCH_PAGE               "Search page"
#define SID_SHORTCUT_SELECT_ALL                "Select all"
#define SID_SHORTCUT_SELECT_ENTRY              "Select entry"
#define SID_SHORTCUT_SHOW_NOTES                "Show notes"
#define SID_SHORTCUT_KEEP_SYNCED               "Toggle sync always"
#define SID_SHORTCUT_SYNC_PAGE_WITH_CONTENTS   "Sync page with contents"
#define SID_SHORTCUT_SYNC_CONTENTS_WITH_PAGE   "Sync contents with page"
#define SID_SHORTCUT_TOGGLE_INTERFACE          "Toggle interface"
#define SID_SHORTCUT_SHOW_LOGS                 "Show logs"

#define SID_SEARCH_IGNORE_DIACRITICS           "Ignore diacritics"
#define SID_SEARCH_TYPE_REGEX                  "Regex"
#define SID_SEARCH_WHOLE_WORD                  "Whole word"
#define SID_SEARCH_ARABIC_CONTEXT_STYLE        "Arabic context style"
#define SID_SEARCH_DIACRITICS                  "Diacritics"

#define SID_HEADSEARCH_RESULTS_FONT            "Results Arabic font"
#define SID_HEADSEARCH_STEP                    "Step"
#define SID_HEADSEARCH_DEBUG                   "Debug"
#define SID_HEADSEARCH_FOCUS_TABLE             "Focus table"
#define SID_HEADSEARCH_LAYOUT                  "Vertical layout"
#define SID_HEADSEARCH_NEW_TAB                 "New tab"
#define SID_HEADSEARCH_GO_TAB                  "Go to new tab"

#define SID_LOCALSEARCH_SHOW_ALL               "Show all results"
#define SID_LOCALSEARCH_IGNORE_DIACRITICS      "Ignore diacritics"
#define SID_LOCALSEARCH_WHOLE_WORD             "Whole word"
#define SID_LOCALSEARCH_FORCE_LTR              "Force LTR"
#define SID_LOCALSEARCH_TYPE_REGEX             "Regex"

#define SID_FULLSEARCH_ONE_ROW                 "One row"
#define SID_FULLSEARCH_RESULTS_FONT            "Results Arabic font"
#define SID_FULLSEARCH_DEBUG                   "Debug"
#define SID_FULLSEARCH_FRAGMENT_SIZE           "Fragment size"
#define SID_FULLSEARCH_INCLUDE_HEADS           "Include heads"
#define SID_FULLSEARCH_HEAD_BACKGROUND         "Head word background"
#define SID_FULLSEARCH_HEAD_TEXT               "Head text"
#define SID_FULLSEARCH_VIEWER_SIZE             "Viewer size"
#define SID_FULLSEARCH_VIEWER_POSITION         "Viewer position"
#define SID_FULLSEARCH_STEP                    "Step"
#define SID_FULLSEARCH_WHOLE_WORD              "Whole word"
#define SID_FULLSEARCH_DIACRITICS              "Ignore diacritics"
#define SID_FULLSEARCH_TYPE_REGEX              "Regex"
#define SID_FULLSEARCH_NEW_TAB                 "Open in new tab"
#define SID_FULLSEARCH_GO_TAB                  "Go to new tab"
#define SID_ROOTSEARCH_NEW_TAB                 "New tab"
#define SID_ROOTSEARCH_GO_TAB                  "Go to new tab"

#define SID_ARABIC_FONT_NAME                   "Font"
#define SID_ARABIC_FONT_SIZE                   "Size"

#define SID_TABBAR_NUMBER                      "Number"
#define SID_TABBAR_MOVEABLE                    "Moveable"


#define SID_CONTENTS_BACKGROUND                "Background"
#define SID_CONTENTS_DEBUG                     "Debug"
#define SID_CONTENTS_EXPAND                    "Expand"
#define SID_CONTENTS_MOVE_DOWN                 "Move down"
#define SID_CONTENTS_MOVE_UP                   "Move up"
#define SID_CONTENTS_STANDARD_FONT             "Standard font"
#define SID_CONTENTS_ARABIC_FONT               "Arabic font"
#define SID_CONTENTS_KEEP_FOCUS                "Keep focus"
#define SID_CONTENTS_SHOWHEAD                  "Show head"
#define SID_CONTENTS_SHOWENTRY                 "Show entry"
#define SID_CONTENTS_SHOWSUPPLEMENT            "Show supplement"
#define SID_CONTENTS_ROMAN_ITYPES              "Verb form number Roman"
#define SID_LOGGING_FILE                       "Logfile"
#define SID_LOGGING_MAXSIZE                    "Maximum size"
#define SID_LOGGING_LEVEL                      "Level"
#define SID_LOGGING_ARCHIVES                   "Archive"
#define SID_LOGGING_VIEWER_MAXLINES            "Viewer lines"
#define SID_LOGGING_VIEWER_INTERVAL            "Viewer refresh interval"
#define SID_LOGGING_ROTATE                     "Rotate"
