#define ID_SYSTEM_EXIT     "Exit"
#define ID_SYSTEM_COLOR    "Color"
#define ID_SYSTEM_DATABASE "Database"
#define ID_SYSTEM_DEFAULT_MAP "Buckwwalter"
#define ID_SYSTEM_DOCKED    "Docked"
#define ID_SYSTEM_FOCUS_TAB "Focus tab"
#define ID_SYSTEM_INTERFACE "Interface"
#define ID_SYSTEM_KEYMAPS   "Keymaps"
#define ID_SYSTEM_NAV_MODE  "Nav mode"


#define ID_SPLASH_DELAY "Delay"
#define ID_SPLASH_ENABLED "Enabled"
#define ID_SPLASH_LOCATION "Location"


#define ID_ENTRY_BACK "Back"
#define ID_ENTRY_CSS  "CSS"
#define ID_ENTRY_CLEAN "Clean"
#define ID_ENTRY_CLEAR_SCENE "Clear scene"
#define ID_ENTRY_DEBUG "Debug"
#define ID_ENTRY_FIND  "Find"
#define ID_ENTRY_FIND_NEXT "Find next"
#define ID_ENTRY_FONT       "Font"
#define ID_ENTRY_FORWARD  "Forward"
#define ID_ENTRY_FONT_SIZE "Font size"
#define ID_ENTRY_HOME       "Home"
#define ID_ENTRY_MARGIN     "Margin"
#define ID_ENTRY_MOVE_FOCUS_UP "Move focus up"
#define ID_ENTRY_MOVE_FOCUS_DOWN "Move focus down"
#define ID_ENTRY_NARROW  "Narrow"
#define ID_ENTRY_SHOW    "Show"
#define ID_ENTRY_STEP    "Step"
#define ID_ENTRY_SUPPLEMENT_BACKGROUND_COLOR "Supplement background color"
#define ID_ENTRY_TEXT_WIDTH "Text width"
#define ID_ENTRY_WIDEN   "Widen"
#define ID_ENTRY_XSLT   "XSLT"
#define ID_ENTRY_ZOOM_IN "Zoom in"
#define ID_ENTRY_ZOOM_OUT "Zoom out"
#define ID_ENTRY_PRINT_CSS "Print Css"
#define ID_ENTRY_DUMP_HTML "Save HTML"
#define ID_ENTRY_DUMP_XML  "Save XML"
#define ID_ENTRY_DUMP_OUTPUT_HTML "Dump output HTML"

#define ID_NOTES_ENABLED "Enabled"
